### ISSUE TITLE
Praca domowa 6

### ISSUE THREAD

**Issue by krzysztofspalinski** [mini-pw/2021L-ExploratoryDataAnalysis#166]
Zaimplementuj swoje rozwiązanie [Pracy domowej 2](https://github.com/mini-pw/2021L-ExploratoryDataAnalysis/issues/35) w Pythonie w pakiecie `matplotlib` lub `seaborn`. Wymagania co do raportu (w formie Jupyter Notebooka) są identyczne jak w PD2, ale punktacja zależy wyłącznie od jakości wykresu (4 punkty) oraz czystości kodu (1 punkt). Przypominam o wyszukiwaniu rozwiązań w Google i na Stackoverflow, ale jeśli skopiujecie wyjątkowo skomplikowany fragment kodu to rozszyfrujcie co robi i opiszcie to w komentarzu. 

Termin oddania pracy: **środa, 2 czerwca, godzina 23:59**.

**Comment by stepiend** [comment]
Czy powinniśmy szukać nowych wykresów czy użyć wykresów z PD2?
